version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: newsbot-postgres
    environment:
      POSTGRES_DB: newsbot
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_pass
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER} -h 127.0.0.1 -p 5432 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s
    restart: unless-stopped

volumes:
  dbdata:
