apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: None
    resources:
      - group: ""
        resources: ["secrets"]
  - level: Metadata
    verbs: ["get","list","watch"]
  - level: RequestResponse
    verbs: ["create","update","patch","delete","deletecollection"]
    resources:
      - group: ""
        resources: ["pods","deployments","configmaps","secrets","serviceaccounts"]
      - group: "apps"
        resources: ["deployments","statefulsets","daemonsets","replicasets"]
      - group: "argoproj.io"
        resources: ["rollouts","applications"]
  - level: Metadata
    userGroups: ["system:serviceaccounts:kube-system"]
