route:
  receiver: null-receiver
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 2h
  routes:
    - matchers:
        - severity="critical"
      receiver: slack
      continue: false
    - receiver: webhook

receivers:
  - name: null-receiver
  - name: webhook
    webhook_configs:
      - url: ${ALERT_WEBHOOK_URL:-http://example.com/hook}
  - name: slack
    slack_configs:
      - api_url: ${SLACK_WEBHOOK_URL:-https://hooks.slack.com/services/T000/B000/XXXXX}
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'

templates: []
