{{- if .Values.rollouts.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "newsbot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "newsbot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "newsbot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    canary:
      canaryService: {{ include "newsbot.fullname" . }}-canary
      stableService: {{ include "newsbot.fullname" . }}
      trafficRouting:
{{ toYaml .Values.rollouts.canary.trafficRouting | indent 8 }}
      steps:
{{ toYaml .Values.rollouts.canary.steps | indent 8 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "newsbot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
{{- with .Values.podAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ include "newsbot.fullname" . }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          env:
{{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
{{- end }}
{{- range $k, $v := .Values.secretEnv }}
            - name: {{ $k }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "newsbot.fullname" $ }}
                  key: {{ $k | lower }}
{{- end }}
          readinessProbe:
            httpGet: { path: /health/db, port: http }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 12 }}
{{- end }}
      volumes:
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 8 }}
{{- end }}
{{- end }}
