{{- if .Values.rollouts.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "newsbot.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "newsbot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "newsbot.fullname" . }}-canary
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "newsbot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- end }}
