global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alerts.rules.yml
  - costs.rules.yml

scrape_configs:
  - job_name: app
    static_configs:
      - targets: ["newsbot-app:8080"]
    metrics_path: /metrics

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
