global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alerts.rules.yml

scrape_configs:
  - job_name: app
    metrics_path: /metrics
    static_configs:
      - targets:
          - newsbot-app:8080

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
