apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newsbot-prod
resources:
  - ../../rendered
patches:
  - target:
      kind: Rollout
      name: .*
    patch: |
      - op: add
        path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchExpressions/-
        value:
          key: topology.kubernetes.io/region
          operator: In
          values: ["us-east-1"]
      - op: add
        path: /spec/template/spec/priorityClassName
        value: critical-apps
