version: "3.9"

networks:
  compose_default:
    external: true

services:
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts.rules.yml:/etc/prometheus/alerts.rules.yml:ro
      - ./prometheus/costs.rules.yml:/etc/prometheus/costs.rules.yml:ro
    ports: ["9090:9090"]
    networks: [compose_default]

  grafana:
    image: grafana/grafana:10.4.4
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-admin}
    volumes:
      - ./grafana/provisioning/datasources/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./grafana/provisioning/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
    ports: ["3000:3000"]
    depends_on: [prometheus]
    networks: [compose_default]

  loki:
    image: grafana/loki:3.1.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports: ["3100:3100"]
    networks: [compose_default]

  promtail:
    image: grafana/promtail:3.1.0
    container_name: promtail
    volumes:
      - ./promtail/promtail.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
    command: -config.file=/etc/promtail/config.yml
    networks: [compose_default]
