server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets: [localhost]
        labels:
          job: nginx
          __path__: /var/log/nginx/access.json

  - job_name: app
    static_configs:
      - targets: [localhost]
        labels:
          job: app
          __path__: /var/log/containers/*newsbot-app*.log

  - job_name: falco
    static_configs:
      - targets: [localhost]
        labels:
          job: falco
          __path__: /var/log/containers/*falco*.log

  - job_name: kube-audit
    static_configs:
      - targets: [localhost]
        labels:
          job: kube-audit
          __path__: /var/log/kubernetes/audit.log
