name: billing-recon

on:
  schedule:
    - cron: '15 3 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.STAGE_DB_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Run billing reconciliation
        run: ./gradlew :app:runRecon --console=plain
      - name: Upload reconciliation report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: billing-recon-result
          path: recon_result.txt
          if-no-files-found: warn
