name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Fail on merge conflict markers
        run: |
          if git grep -nE '^(<<<<<<<|=======|>>>>>>>)' -- . ':!**/.github/**' ; then
            echo "Merge conflict markers found. Please resolve."; exit 1;
          fi

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Lint (ktlint + detekt)
        run: ./gradlew --no-daemon --stacktrace ktlintCheck detekt

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: --no-daemon --stacktrace clean build

      - name: Core tests
        run: ./gradlew :core:test --console=plain

      - name: App tests
        run: ./gradlew :app:test --console=plain

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: quality-reports
          path: |
            **/build/reports/ktlint/**/*
            **/build/reports/detekt/**/*
            **/build/reports/tests/**/*
          if-no-files-found: ignore
