name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Fail on merge conflict markers
        run: |
          if git grep -nE '^(<<<<<<<|=======|>>>>>>>)' -- . ':!**/.github/**' ; then
            echo "Merge conflict markers found. Please resolve conflicts."; exit 1;
          else
            echo "No conflict markers found.";
          fi

      - name: Build
        run: ./gradlew build
