name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Fail on merge conflict markers
        run: |
          if git grep -nE '^(<<<<<<<|=======|>>>>>>>)' -- . ; then
            echo "Merge conflict markers found. Please resolve conflicts." && exit 1
          fi

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: --no-daemon --stacktrace clean build

      - name: Core tests
        run: ./gradlew :core:test --console=plain

      - name: App tests
        run: ./gradlew :app:test --console=plain

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/build/test-results/**/*.xml
            **/build/reports/tests/**/*
          if-no-files-found: ignore
