name: DB Migrate

on:
  workflow_dispatch:
  push:
    paths:
      - 'storage/**'
      - 'storage/src/**'
      - 'storage/src/main/resources/db/migration/**'

permissions:
  contents: read

jobs:
  flyway:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: newsbot
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app_pass
        options: >-
          --health-cmd "pg_isready -U app -d newsbot"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - name: Wait for Postgres
        run: sleep 15
      - name: Run Flyway migrations
        run: |
          ./gradlew :storage:flywayMigrateIfDb \
            -PwithDb=true \
            -Pflyway.url=jdbc:postgresql://localhost:${{ job.services.postgres.ports[5432] }}/newsbot \
            -Pflyway.user=app -Pflyway.password=app_pass -Pflyway.schemas=public \
            --console=plain
      - name: Upload Gradle logs
        uses: actions/upload-artifact@v4
        with:
          name: gradle-logs
          path: |
            **/build/reports/**
            **/build/logs/**
          retention-days: 7
