name: Governance Gate (Policies + Evidence + Risk Score)

on:
  pull_request:
    paths:
      - 'helm/**'
      - 'k8s/**'
      - 'governance/**'
      - '.github/workflows/**'
      - 'tools/**'
  workflow_dispatch: {}

permissions:
  contents: read
  security-events: write

jobs:
  policies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Helm & Conftest
        run: |
          sudo apt-get update && sudo apt-get install -y curl jq
          curl -sSLo conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/download/v0.51.0/conftest_Linux_x86_64.tar.gz
          tar -xzf conftest.tar.gz && sudo install -m 0755 conftest /usr/local/bin/conftest
          curl -sSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod +x get_helm.sh && ./get_helm.sh
      - name: Run policy checks
        run: bash tools/governance/policy_check.sh

  evidence:
    runs-on: ubuntu-latest
    needs: policies
    env:
      EVID_SARIF_CODEQL_URL:   ${{ secrets.EVID_SARIF_CODEQL_URL }}
      EVID_TRIVY_FS_URL:       ${{ secrets.EVID_TRIVY_FS_URL }}
      EVID_TRIVY_IMG_URL:      ${{ secrets.EVID_TRIVY_IMG_URL }}
      EVID_GITLEAKS_URL:       ${{ secrets.EVID_GITLEAKS_URL }}
      EVID_CV_REPORT_URL:      ${{ secrets.EVID_CV_REPORT_URL }}
      EVID_FINOPS_URL:         ${{ secrets.EVID_FINOPS_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Install jq & python
        run: sudo apt-get update && sudo apt-get install -y jq python3
      - name: Collect evidence
        run: bash tools/governance/collect_evidence.sh
      - name: Risk score
        run: python3 tools/governance/risk_score.py
      - name: Upload governance report
        uses: actions/upload-artifact@v4
        with:
          name: governance-report
          path: .governance/**
          retention-days: 30
