name: Governance Daily

on:
  schedule:
    - cron: "23 3 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq python3
      - name: Collect evidence (secure sources via secrets)
        env:
          EVID_SARIF_CODEQL_URL:   ${{ secrets.EVID_SARIF_CODEQL_URL }}
          EVID_TRIVY_FS_URL:       ${{ secrets.EVID_TRIVY_FS_URL }}
          EVID_TRIVY_IMG_URL:      ${{ secrets.EVID_TRIVY_IMG_URL }}
          EVID_GITLEAKS_URL:       ${{ secrets.EVID_GITLEAKS_URL }}
          EVID_CV_REPORT_URL:      ${{ secrets.EVID_CV_REPORT_URL }}
          EVID_FINOPS_URL:         ${{ secrets.EVID_FINOPS_URL }}
        run: |
          bash tools/governance/collect_evidence.sh
          python3 tools/governance/risk_score.py
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: governance-daily
          path: .governance/**
          retention-days: 14
