name: Secrets Drift Check

on:
  schedule:
    - cron: "9 2 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check required secrets
        run: |
          req=(VAULT_TRANSIT_BASE VAULT_TOKEN VAULT_KEY_ID)
          missing=0
          for s in "${req[@]}"; do
            if [ -z "${!s:-}" ]; then echo "::warning ::Secret $s missing"; missing=$((missing+1)); fi
          done
          if [ "$missing" -gt 0 ]; then
            echo "::notice ::Set missing secrets in repository/environment settings"
          fi
