name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: "AWS region"
        required: true
        default: "eu-central-1"
      s3_backups_bucket:
        description: "S3 bucket for backups (unique name)"
        required: true

permissions:
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    environment:
      name: staging
    env:
      KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ inputs.aws_region }}
      - name: Write kubeconfig from secret
        if: env.KUBECONFIG_BASE64 != ''
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG_BASE64" | base64 --decode > ~/.kube/config
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        env:
          TF_VAR_aws_region: ${{ inputs.aws_region }}
          TF_VAR_s3_backups_bucket: ${{ inputs.s3_backups_bucket }}
        run: terraform apply -auto-approve -input=false
