name: Trivy Security Scans

on:
  pull_request:
  push:
    branches: ["main"]
  schedule:
    - cron: "15 4 * * 1"
  workflow_dispatch: {}

permissions:
  contents: read
  security-events: write

jobs:
  fs-scan:
    name: Trivy FS (deps/vulns)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy FS scan (SARIF)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-fs.sarif'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          vuln-type: 'os,library'
          exit-code: '0'
          trivyignores: '.trivyignore'

      - name: Upload SARIF (FS)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif
          category: trivy-fs

  image-scan:
    name: Trivy Image (Dockerfile → image)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (local)
        run: docker build -t newsbot-app:pr -f Dockerfile .

      - name: Trivy Image (SARIF)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'newsbot-app:pr'
          scan-type: 'image'
          format: 'sarif'
          output: 'trivy-image.sarif'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '0'
          trivyignores: '.trivyignore'

      - name: Upload SARIF (Image)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif
          category: trivy-image

  config-scan:
    name: Trivy Config (IaC)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Trivy Config (compose/monitoring)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'config'
          format: 'sarif'
          output: 'trivy-config.sarif'
          severity: 'HIGH,CRITICAL'
          exit-code: '0'
          scan-ref: '.'

      - name: Upload SARIF (Config)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-config.sarif
          category: trivy-config
