name: ZAP Baseline Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    env:
      TARGET: ${{ secrets.STAGE_BASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: OWASP ZAP Baseline
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: ${{ env.TARGET }}
          fail_action: true
          cmd_options: '-a -m 5 -t ${{ env.TARGET }}'

      - name: Upload ZAP report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-baseline-report
          path: zap_report.html
